services:
  db:
    image: postgres:18-alpine
    container_name: lunastore_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-lunastore}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - storenetwork
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-lunastore}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  admin:
    image: registry.myslivets.com/myslivets/project-luna/lunastore:latest
    container_name: lunastore_admin
    command: gunicorn lunastore.wsgi:application --bind 0.0.0.0:8088 --workers 3
    environment:
      DJANGO_ROOT_URLCONF: lunastore.urls_private
    expose:
      - "8088"
    networks:
      - storenetwork
    restart: on-failure
    env_file:             
      - .env             
    depends_on:           
      - db
    volumes: 
      - static_volume:/app/staticfiles_build
      - media_volume:/app/media

  web:
    image: registry.myslivets.com/myslivets/project-luna/lunastore:latest
    container_name: lunastore_web
    env_file:
      - .env
    depends_on:         
      - db
    expose:
      - "9088"
    restart: unless-stopped
    networks:
      - storenetwork
    volumes:
      - static_volume:/app/staticfiles_build
      - media_volume:/app/media

  api:
    image: registry.myslivets.com/myslivets/project-luna/lunastore:latest
    container_name: lunastore_api
    environment:
      DJANGO_ROOT_URLCONF: lunastore.urls_api
    expose:
      - "7088"
    env_file:
      - .env
    depends_on:         
      - db
    restart: unless-stopped
    networks:
      - storenetwork 
    volumes: 
      - static_volume:/app/staticfiles_build
      - media_volume:/app/media

  nginx:
    image: nginx:alpine
    container_name: lunastore_nginx
    ports:
      - "80:80"
      - "8088:8088"   # admin port for SSO
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - web
      - admin
      - api
    restart: unless-stopped
    networks:
      - storenetwork

networks:
  storenetwork:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  pg_data: