services:
  admin:
    build:
      context: .
      target: base 
    container_name: lunaStoreAdmin
    command: python manage.py runserver 0.0.0.0:8088
    volumes:
      - ./:/app
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8088:8088"
    environment:
      DJANGO_ROOT_URLCONF: lunastore.urls_private
      DJANGO_SETTINGS_MODULE: lunastore.settings
      PYTHONPATH: /app
    networks:
      - storenetwork
    restart: on-failure

  web:
    build:
      context: .
      target: web
    container_name: lunaStore
    environment:
      PYTHONPATH: /app
      DJANGO_SETTINGS_MODULE: lunastore.settings
      DJANGO_ROOT_URLCONF: lunastore.urls
    working_dir: /app
    ports:
      - "9088:9088"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:9088
    restart: unless-stopped
    networks:
      - storenetwork
    volumes:
      - .:/app

networks:
  storenetwork:
    driver: bridge