# Generated by Django 5.2.3 on 2025-11-08 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=140)),
                ('shortcode', models.CharField(default='index.php', max_length=50)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=1400)),
                ('slogan', models.CharField(blank=True, max_length=240, null=True)),
                ('icon', models.FileField(max_length=140, null=True, upload_to='staticfiles/ugc/app_icons')),
                ('price', models.IntegerField(default=0)),
                ('screenshots', models.JSONField(blank=True, default=list, null=True)),
                ('developer_site', models.URLField(blank=True, max_length=160, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('is_under_dmca', models.BooleanField(default=False)),
                ('published', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.category')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('file', models.FileField(max_length=80, null=True, upload_to='staticfiles/ugc/distributions')),
                ('url', models.URLField(max_length=140, null=True)),
                ('changelog', models.CharField(max_length=210)),
                ('published', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.application')),
            ],
            options={
                'verbose_name': 'Дистрибуция',
                'verbose_name_plural': 'Дистрибуции',
                'ordering': ['app', 'published'],
            },
        ),
    ]
