# Generated by Django 6.0 on 2026-01-17 21:56

import apps.marketplace.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=140)),
                ('shortcode', models.CharField(default='index.php', max_length=50)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('description', models.CharField(max_length=1400, verbose_name='Описание')),
                ('slogan', models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган')),
                ('icon', models.ImageField(max_length=140, null=True, upload_to=apps.marketplace.models.get_icon_path, verbose_name='Иконка')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('screenshots', models.JSONField(blank=True, default=list, null=True, verbose_name='Скриншоты')),
                ('developer_site', models.URLField(blank=True, max_length=160, null=True, verbose_name='Сайт разработчика')),
                ('is_demo', models.BooleanField(default=False)),
                ('is_under_dmca', models.BooleanField(default=False)),
                ('published', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
                'ordering': ['title'],
                'permissions': [('set_dmca_flag', 'Can set DMCA flag on application'), ('set_demo_flag', 'Can set demo flag on application')],
            },
        ),
        migrations.CreateModel(
            name='AppEditRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('description', models.CharField(max_length=1400, verbose_name='Описание')),
                ('slogan', models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган')),
                ('icon', models.ImageField(max_length=140, null=True, upload_to=apps.marketplace.models.get_icon_path, verbose_name='Иконка')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('screenshots', models.JSONField(blank=True, default=list, null=True, verbose_name='Скриншоты')),
                ('developer_site', models.URLField(blank=True, max_length=160, null=True, verbose_name='Сайт разработчика')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор правки')),
                ('target_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='marketplace.application', verbose_name='Редактируемое приложение')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Заявка на редактирование',
                'verbose_name_plural': 'Заявки на редактирование',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppCreateRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('description', models.CharField(max_length=1400, verbose_name='Описание')),
                ('slogan', models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган')),
                ('icon', models.ImageField(max_length=140, null=True, upload_to=apps.marketplace.models.get_icon_path, verbose_name='Иконка')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('screenshots', models.JSONField(blank=True, default=list, null=True, verbose_name='Скриншоты')),
                ('developer_site', models.URLField(blank=True, max_length=160, null=True, verbose_name='Сайт разработчика')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_requests', to=settings.AUTH_USER_MODEL, verbose_name='Автор заявки')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Заявка на создание',
                'verbose_name_plural': 'Заявки на создание',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('file', models.FileField(max_length=80, null=True, upload_to='ugc/distributions')),
                ('url', models.URLField(max_length=140, null=True)),
                ('changelog', models.CharField(max_length=210)),
                ('published', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.application')),
            ],
            options={
                'verbose_name': 'Дистрибуция',
                'verbose_name_plural': 'Дистрибуции',
                'ordering': ['app', 'published'],
            },
        ),
    ]
