# Generated by Django 5.2.7 on 2025-10-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='screenshots',
            field=models.JSONField(default=list),
        ),
    ]
