# Generated by Django 5.2.3 on 2025-11-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['title'], 'permissions': [('set_dmca_flag', 'Can set DMCA flag on application'), ('set_demo_flag', 'Can set demo flag on application')], 'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
    ]
