# Generated by Django 6.0 on 2026-01-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeditrequests',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Заявка на изменение',
                'verbose_name_plural': 'Заявки на изменения'},
        ),
    ]
