# Generated by Django 6.0 on 2026-01-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_application_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.FileField(max_length=140, null=True, upload_to='media/ugc/app_icons'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='file',
            field=models.FileField(max_length=80, null=True, upload_to='media/ugc/distributions'),
        ),
    ]
