# Generated by Django 6.0 on 2026-01-22 15:21

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_appeditrequests_options'),
    ]

    operations = [
        TrigramExtension(),
    ]
