# Generated by Django 5.2.3 on 2025-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['title'], 'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ['app', 'published'], 'verbose_name': 'Дистрибуция', 'verbose_name_plural': 'Дистрибуции'},
        ),
        migrations.AddField(
            model_name='category',
            name='shortcode',
            field=models.CharField(default='index.php', max_length=50),
        ),
    ]
