# Generated by Django 6.0 on 2026-01-17 12:28

import apps.marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_application_icon_alter_distribution_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.FileField(max_length=140, null=True, upload_to=apps.marketplace.models.get_icon_path),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='file',
            field=models.FileField(max_length=80, null=True, upload_to='ugc/distributions'),
        ),
    ]
