# Generated by Django 6.0 on 2026-01-22 15:41

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20260122_1521'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=[
                    'title',
                    'description',
                    'slogan'],
                name='app_trgm_idx',
                opclasses=[
                    'gin_trgm_ops',
                    'gin_trgm_ops',
                    'gin_trgm_ops']),
        ),
    ]
