# Generated by Django 5.2.3 on 2025-10-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_application_options_alter_distribution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.FileField(max_length=140, null=True, upload_to='staticfiles/ugc/app_icons'),
        ),
        migrations.AlterField(
            model_name='application',
            name='screenshots',
            field=models.FileField(max_length=525, null=True, upload_to='statisfiles/ugc/screenshots'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='file',
            field=models.FileField(max_length=80, null=True, upload_to='staticfiles/ugc/distributions'),
        ),
    ]
