# Generated by Django 6.0 on 2026-02-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_appreportrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreportrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'Новая'), ('resolved', 'Решено'), ('dismissed', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appreportrequests',
            name='reason',
            field=models.CharField(choices=[('1', 'PAGE_REPORTAPP_REASON_MALWARE'), ('2', 'PAGE_REPORTAPP_REASON_INCORRECT'), ('3', 'PAGE_REPORTAPP_REASON_OTHER')], default='1', max_length=1),
        ),
    ]
