# Generated by Django 5.2.3 on 2025-10-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_application_icon_alter_application_screenshots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='screenshots',
            field=models.FileField(max_length=525, null=True, upload_to='staticfiles/ugc/screenshots'),
        ),
    ]
