# Generated by Django 6.0 on 2026-02-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_appreportrequests_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreportrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'Новая'), ('resolved', 'Рассматривается'), ('dismissed', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
