# Generated by Django 5.2.3 on 2025-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_application_screenshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='screenshots',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
