# Generated by Django 6.0 on 2026-03-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_appcreaterequests_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shortcode',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(
                blank=True,
                max_length=140,
                null=True,
                verbose_name='Иконка'),
        ),
    ]
