# Generated by Django 5.2.3 on 2025-10-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_application_screenshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='developer_site',
            field=models.URLField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='slogan',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.CharField(max_length=1400),
        ),
    ]
