# Generated by Django 6.0 on 2026-03-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_remove_category_shortcode_category_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appreportrequests',
            options={
                'verbose_name': 'PAGE_REPORTAPP_TITLE',
                'verbose_name_plural': 'PAGE_REPORTAPP_TITLE_PATH'},
        ),
    ]
