# Generated by Django 5.2.3 on 2025-10-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_application_developer_site_application_is_demo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_under_dmca',
            field=models.BooleanField(default=False),
        ),
    ]
