# Generated by Django 5.2.3 on 2025-10-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_application_is_under_dmca'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
