# Generated by Django 6.0 on 2026-03-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_appreportrequests_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appcreaterequests',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='appeditrequests',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='application',
            name='icon',
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='icon_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='icon_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='icon_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='icon_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='icon_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='icon_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
