# Generated by Django 6.0 on 2026-03-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_remove_appcreaterequests_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='file',
        ),
        migrations.AddField(
            model_name='distribution',
            name='cdn_file_id',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name='ID файла в CDN'),
        ),
    ]
