# Generated by Django 5.2.3 on 2025-10-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_application_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
