# Generated by Django 6.0 on 2026-03-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_appcreaterequests_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcreaterequests',
            name='requirements',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AlterField(
            model_name='appeditrequests',
            name='requirements',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AlterField(
            model_name='application',
            name='requirements',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
    ]
