# Generated by Django 6.0 on 2026-03-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_alter_appcreaterequests_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcreaterequests',
            name='original_author',
            field=models.CharField(
                blank=True,
                default='неизвестен',
                max_length=80,
                null=True,
                verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='original_author',
            field=models.CharField(
                blank=True,
                default='неизвестен',
                max_length=80,
                null=True,
                verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='application',
            name='original_author',
            field=models.CharField(
                blank=True,
                default='неизвестен',
                max_length=80,
                null=True,
                verbose_name='Автор'),
        ),
    ]
