# Generated by Django 6.0 on 2026-03-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_appcreaterequests_original_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcreaterequests',
            name='original_author',
            field=models.CharField(
                blank=True,
                default='неизвестен',
                max_length=80,
                null=True,
                verbose_name='Оригинальный автор'),
        ),
        migrations.AlterField(
            model_name='appeditrequests',
            name='original_author',
            field=models.CharField(
                blank=True,
                default='неизвестен',
                max_length=80,
                null=True,
                verbose_name='Оригинальный автор'),
        ),
        migrations.AlterField(
            model_name='application',
            name='original_author',
            field=models.CharField(
                blank=True,
                default='неизвестен',
                max_length=80,
                null=True,
                verbose_name='Оригинальный автор'),
        ),
    ]
