# Generated by Django 6.0 on 2026-04-12 07:47

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_alter_appcreaterequests_original_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appcreaterequests',
            name='description_be',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='description_en',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='description_ru',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='description_uk',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='requirements_be',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='requirements_en',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='requirements_ru',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='requirements_uk',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='slogan_be',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='slogan_en',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='slogan_ru',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='slogan_uk',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='title_be',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='title_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='title_uk',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='application',
            name='description_be',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='application',
            name='description_en',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='application',
            name='description_ru',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='application',
            name='description_uk',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='application',
            name='requirements_be',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='application',
            name='requirements_en',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='application',
            name='requirements_ru',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='application',
            name='requirements_uk',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='application',
            name='slogan_be',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='application',
            name='slogan_en',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='application',
            name='slogan_ru',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='application',
            name='slogan_uk',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='application',
            name='title_be',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='application',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='application',
            name='title_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='application',
            name='title_uk',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_be',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_be',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='changelog_be',
            field=models.CharField(max_length=210, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='changelog_en',
            field=models.CharField(max_length=210, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='changelog_ru',
            field=models.CharField(max_length=210, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='changelog_uk',
            field=models.CharField(max_length=210, null=True),
        ),
        migrations.AddIndex(
            model_name='application',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_ru', 'description_ru', 'slogan_ru'], name='app_trgm_idx-ru', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='application',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_en', 'description_en', 'slogan_en'], name='app_trgm_idx-en', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='application',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_uk', 'description_uk', 'slogan_uk'], name='app_trgm_idx-uk', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='application',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_be', 'description_be', 'slogan_be'], name='app_trgm_idx-be', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
