# Generated by Django 6.0 on 2026-04-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_appcreaterequests_description_be_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeditrequests',
            name='description_be',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='description_en',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='description_ru',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='description_uk',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='requirements_be',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='requirements_en',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='requirements_ru',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='requirements_uk',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='slogan_be',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='slogan_en',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='slogan_ru',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='slogan_uk',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='title_be',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='title_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='title_uk',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=140, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_be',
            field=models.CharField(max_length=140, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.CharField(max_length=140, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ru',
            field=models.CharField(max_length=140, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_uk',
            field=models.CharField(max_length=140, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_be',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
    ]
