# Generated by Django 6.0 on 2026-04-20 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_appeditrequests_description_be_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ['app', '-published'], 'verbose_name': 'Дистрибуция', 'verbose_name_plural': 'Дистрибуции'},
        ),
        migrations.AlterField(
            model_name='distribution',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='marketplace.application', verbose_name='Приложение'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='changelog',
            field=models.CharField(max_length=210, verbose_name='Список изменений'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='changelog_be',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='changelog_en',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='changelog_ru',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='changelog_uk',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='url',
            field=models.URLField(blank=True, max_length=140, null=True, verbose_name='Внешняя ссылка (если не CDN)'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='version',
            field=models.CharField(max_length=20, verbose_name='Версия'),
        ),
        migrations.CreateModel(
            name='DistributionCreateRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('version', models.CharField(max_length=20, verbose_name='Версия')),
                ('cdn_file_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID файла в CDN')),
                ('url', models.URLField(blank=True, max_length=140, null=True, verbose_name='Внешняя ссылка (если не CDN)')),
                ('changelog', models.CharField(max_length=210, verbose_name='Список изменений')),
                ('virustotal_url', models.URLField(max_length=255, verbose_name='Ссылка на VirusTotal')),
                ('user_hash', models.CharField(max_length=128, verbose_name='Хэш от пользователя (SHA-256)')),
                ('cdn_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='Хэш от CDN')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='marketplace.application', verbose_name='Приложение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_requests', to=settings.AUTH_USER_MODEL, verbose_name='Автор заявки')),
            ],
            options={
                'verbose_name': 'Заявка на дистрибуцию',
                'verbose_name_plural': 'Заявки на дистрибуции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionEditRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('version', models.CharField(max_length=20, verbose_name='Версия')),
                ('cdn_file_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID файла в CDN')),
                ('url', models.URLField(blank=True, max_length=140, null=True, verbose_name='Внешняя ссылка (если не CDN)')),
                ('changelog', models.CharField(max_length=210, verbose_name='Список изменений')),
                ('virustotal_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на VirusTotal')),
                ('user_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='Хэш от пользователя')),
                ('cdn_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='Хэш от CDN')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='marketplace.application', verbose_name='Приложение')),
                ('target_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='marketplace.distribution', verbose_name='Редактируемая дистрибуция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='Автор правки')),
            ],
            options={
                'verbose_name': 'Заявка на изменение дистрибуции',
                'verbose_name_plural': 'Заявки на изменения дистрибуций',
                'ordering': ['-created_at'],
            },
        ),
    ]
