# Generated by Django 6.0 on 2026-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace',
         '0019_alter_distribution_options_alter_distribution_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributioncreaterequests',
            name='changelog_be',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AddField(
            model_name='distributioncreaterequests',
            name='changelog_en',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AddField(
            model_name='distributioncreaterequests',
            name='changelog_ru',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AddField(
            model_name='distributioncreaterequests',
            name='changelog_uk',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AddField(
            model_name='distributioneditrequests',
            name='changelog_be',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AddField(
            model_name='distributioneditrequests',
            name='changelog_en',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AddField(
            model_name='distributioneditrequests',
            name='changelog_ru',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AddField(
            model_name='distributioneditrequests',
            name='changelog_uk',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
    ]
