# Generated by Django 6.0 on 2026-04-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_alter_distributioncreaterequests_cdn_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributioncreaterequests',
            name='user_hash',
        ),
        migrations.RemoveField(
            model_name='distributioneditrequests',
            name='user_hash',
        ),
    ]
