# Generated by Django 6.0 on 2026-05-18 16:26

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_category_is_admin_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appcreaterequests',
            name='description_kk',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='requirements_kk',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='slogan_kk',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='appcreaterequests',
            name='title_kk',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='description_kk',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='requirements_kk',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='slogan_kk',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='title_kk',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='application',
            name='description_kk',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='application',
            name='requirements_kk',
            field=models.CharField(max_length=1400, null=True, verbose_name='Системные требования'),
        ),
        migrations.AddField(
            model_name='application',
            name='slogan_kk',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='application',
            name='title_kk',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_kk',
            field=models.CharField(max_length=140, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='changelog_kk',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AddField(
            model_name='distributioncreaterequests',
            name='changelog_kk',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AddField(
            model_name='distributioneditrequests',
            name='changelog_kk',
            field=models.CharField(max_length=210, null=True, verbose_name='Список изменений'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_kk', 'description_kk', 'slogan_kk'], name='app_trgm_idx-kk', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
