# Generated by Django 6.0 on 2026-05-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_appcreaterequests_description_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcreaterequests',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Демо-версия'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Демо-версия'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Демо-версия'),
        ),
    ]
