# Generated by Django 6.0.3 on 2026-05-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_appcreaterequests_is_demo_appeditrequests_is_demo_and_more'),
        ('marketplace', '0025_problemreportrequests'),
    ]

    operations = [
    ]
