# Generated by Django 6.0 on 2026-05-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_merge_20260526_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemreportrequests',
            options={'verbose_name': 'сообщение о проблеме', 'verbose_name_plural': 'сообщений о проблеме'},
        ),
    ]
