# Generated by Django 6.0 on 2026-05-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_alter_problemreportrequests_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_filename',
            field=models.CharField(
                blank=True,
                help_text="Название файла из папки staticfiles/img/categorybanner (например, 'custom.png')",
                max_length=255,
                null=True,
                verbose_name='Файл баннера'),
        ),
    ]
