# Generated by Django 6.0.3 on 2026-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_alter_problemreportrequests_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcreaterequests',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приложение приватное?'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приложение приватное?'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приложение приватное?'),
        ),
    ]
