# Generated by Django 6.0 on 2026-05-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_appcreaterequests_is_private_and_more'),
        ('marketplace', '0028_category_banner_filename'),
    ]

    operations = [
    ]
