# Generated by Django 6.0.3 on 2026-06-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_merge_20260531_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcreaterequests',
            name='categories',
            field=models.ManyToManyField(
                blank=True,
                related_name='%(class)s_categories',
                to='marketplace.category',
                verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='categories',
            field=models.ManyToManyField(
                blank=True,
                related_name='%(class)s_categories',
                to='marketplace.category',
                verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='application',
            name='categories',
            field=models.ManyToManyField(
                blank=True,
                related_name='%(class)s_categories',
                to='marketplace.category',
                verbose_name='Категории'),
        ),
    ]
