# Generated by Django 6.0.3 on 2026-06-16 17:05

from django.db import migrations


def migrate_category_to_categories(apps, schema_editor):
    Application = apps.get_model('marketplace', 'Application')
    AppCreateRequests = apps.get_model('marketplace', 'AppCreateRequests')
    AppEditRequests = apps.get_model('marketplace', 'AppEditRequests')

    for app_model in [Application, AppCreateRequests, AppEditRequests]:
        for instance in app_model.objects.all():
            if instance.category_id:
                instance.categories.add(instance.category_id)


def reverse_migrate_category_to_categories(apps, schema_editor):
    Application = apps.get_model('marketplace', 'Application')
    AppCreateRequests = apps.get_model('marketplace', 'AppCreateRequests')
    AppEditRequests = apps.get_model('marketplace', 'AppEditRequests')

    for app_model in [Application, AppCreateRequests, AppEditRequests]:
        for instance in app_model.objects.all():
            first_category = instance.categories.first()
            if first_category:
                instance.category = first_category
                instance.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_appcreaterequests_categories_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_category_to_categories,
            reverse_migrate_category_to_categories),
    ]
