# Generated by Django 6.0.3 on 2026-06-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_move_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appcreaterequests',
            name='category',
        ),
        migrations.RemoveField(
            model_name='appeditrequests',
            name='category',
        ),
        migrations.RemoveField(
            model_name='application',
            name='category',
        ),
    ]
