# Generated by Django 6.0.3 on 2026-07-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcreaterequests',
            name='allow_reviews',
            field=models.BooleanField(default=True, verbose_name='Разрешить отзывы'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='allow_reviews',
            field=models.BooleanField(default=True, verbose_name='Разрешить отзывы'),
        ),
        migrations.AddField(
            model_name='application',
            name='allow_reviews',
            field=models.BooleanField(default=True, verbose_name='Разрешить отзывы'),
        ),
    ]
