# Generated by Django 6.0.7 on 2026-07-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0037_alter_badge_predefined_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='release_description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание релиза'),
        ),
        migrations.AddField(
            model_name='distributioncreaterequests',
            name='release_description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание релиза'),
        ),
        migrations.AddField(
            model_name='distributioneditrequests',
            name='release_description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание релиза'),
        ),
    ]
