# Generated by Django 6.0.7 on 2026-09-05 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0039_collection_collectionitem_collectionfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Меньше значение — выше на главной', verbose_name='Порядок')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включён')),
                ('apps_limit', models.PositiveSmallIntegerField(default=4, help_text='Сколько карточек показывать в блоке', verbose_name='Кол-во приложений')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_blocks', to='marketplace.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блок категории на главной',
                'verbose_name_plural': 'Блоки категорий на главной',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
