# Generated by Django 6.0.7 on 2026-09-05 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0040_home_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecategoryblock',
            name='apps_limit',
            field=models.PositiveSmallIntegerField(default=4, help_text='Сколько карточек показывать в блоке (макс. 24)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Кол-во приложений'),
        ),
    ]
