# Generated by Django 6.1.1 on 2026-09-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0040_remove_application_trigram_indexes'),
        ('marketplace', '0041_home_category_block_apps_limit_validators'),
    ]

    operations = [
    ]
