# Generated by Django 6.1.1 on 2026-09-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0042_merge_home_recommendations_trigram_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='lunabox_manifest',
            field=models.JSONField(blank=True, null=True, verbose_name='Инструкция для лунной коробки как ставить приложение'),
        ),
        migrations.AddField(
            model_name='distributioncreaterequests',
            name='lunabox_manifest',
            field=models.JSONField(blank=True, null=True, verbose_name='Инструкция для лунной коробки как ставить приложение'),
        ),
        migrations.AddField(
            model_name='distributioneditrequests',
            name='lunabox_manifest',
            field=models.JSONField(blank=True, null=True, verbose_name='Инструкция для лунной коробки как ставить приложение'),
        ),
    ]
