# Generated by Django 6.1.1 on 2026-09-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0043_distribution_lunabox_manifest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='release_description',
        ),
        migrations.RemoveField(
            model_name='distributioncreaterequests',
            name='release_description',
        ),
        migrations.RemoveField(
            model_name='distributioneditrequests',
            name='release_description',
        ),
        migrations.AlterField(
            model_name='distribution',
            name='lunabox_manifest',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Инструкция для лунной коробки как ставить приложение'),
        ),
        migrations.AlterField(
            model_name='distributioncreaterequests',
            name='lunabox_manifest',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Инструкция для лунной коробки как ставить приложение'),
        ),
        migrations.AlterField(
            model_name='distributioneditrequests',
            name='lunabox_manifest',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Инструкция для лунной коробки как ставить приложение'),
        ),
    ]
