# Generated by Django 6.1.1 on 2026-09-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0044_remove_distribution_release_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='lunabox_manifest',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Инструкция для лунной коробки как ставить приложение - {"type":"program","path":""}'),
        ),
        migrations.AlterField(
            model_name='distributioncreaterequests',
            name='lunabox_manifest',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Инструкция для лунной коробки как ставить приложение - {"type":"program","path":""}'),
        ),
        migrations.AlterField(
            model_name='distributioneditrequests',
            name='lunabox_manifest',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Инструкция для лунной коробки как ставить приложение - {"type":"program","path":""}'),
        ),
    ]
