# Generated by Django 6.1.1 on 2026-09-27 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0045_alter_distribution_lunabox_manifest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='review',
            name='ai_flags',
            field=models.JSONField(blank=True, default=list, verbose_name='AI флаги нарушений'),
        ),
        migrations.AddField(
            model_name='review',
            name='ai_raw_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Сырой ответ ИИ'),
        ),
        migrations.AddField(
            model_name='review',
            name='ai_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Причина вердикта ИИ'),
        ),
        migrations.AddField(
            model_name='review',
            name='ai_score',
            field=models.FloatField(blank=True, null=True, verbose_name='AI индекс нарушений (0.0 - 1.0)'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заметка модератора'),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('approved', 'Одобрен'), ('pending', 'На модерации'), ('rejected', 'Отклонён')], db_default='approved', db_index=True, default='approved', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['application', 'status'], name='marketplace_applica_60a4be_idx'),
        ),
    ]
