# Generated by Django 6.1.1 on 2026-09-26 14:58

from django.conf import settings
from django.db import migrations, models


def populate_rating_cache(apps, schema_editor):
    Application = apps.get_model('marketplace', 'Application')
    Review = apps.get_model('marketplace', 'Review')
    from django.db.models import Avg, Count
    for app in Application.objects.all():
        agg = Review.objects.filter(application=app).aggregate(avg=Avg('rating'), count=Count('id'))
        app.rating_cache = round(agg['avg'] or 0.0, 1)
        app.reviews_count = agg['count'] or 0
        app.save(update_fields=['rating_cache', 'reviews_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0045_alter_distribution_lunabox_manifest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionfavorite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='application',
            name='rating_cache',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='Кэш среднего рейтинга'),
        ),
        migrations.AddField(
            model_name='application',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AddConstraint(
            model_name='collectionfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'collection'), name='unique_collectionfavorite_user_collection'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'application'), name='unique_collectionitem_collection_application'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('application', 'user'), name='unique_review_application_user'),
        ),
        migrations.RunPython(populate_rating_cache, reverse_code=migrations.RunPython.noop),
    ]

