# Generated by Django 6.1.1 on 2026-09-27 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0047_alter_review_options_review_ai_flags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='developer_reply',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Ответ разработчика'),
        ),
        migrations.AddField(
            model_name='review',
            name='developer_reply_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа разработчика'),
        ),
        migrations.AddField(
            model_name='review',
            name='developer_reply_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_replies', to=settings.AUTH_USER_MODEL, verbose_name='Автор ответа'),
        ),
    ]
