# Generated by Django 6.1.1 on 2026-09-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0047_add_review_developer_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReview',
            fields=[
            ],
            options={
                'verbose_name': 'Отзыв на модерации',
                'verbose_name_plural': 'Отзывы на модерации',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketplace.review',),
        ),
    ]
