# Generated by Django 6.0 on 2026-03-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(default='privacy', max_length=50, verbose_name='Тип документа')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=2, verbose_name='Язык')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Юридический документ',
                'verbose_name_plural': 'Юридические документы',
                'unique_together': {('doc_type', 'language')},
            },
        ),
    ]
