# Generated by Django 6.0 on 2026-04-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('uk', 'Українська'), ('be', 'Белорусский')], max_length=2, verbose_name='Язык'),
        ),
    ]
