# Generated by Django 6.0.7 on 2026-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_alter_legaldocument_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('uk', 'Українська'), ('be', 'Белорусский'), ('kz', 'Қазақша')], max_length=2, verbose_name='Язык'),
        ),
    ]
