# Generated by Django 6.0.7 on 2026-08-23 14:17

from django.db import migrations, models


def migrate_kz_to_kk(apps, schema_editor):
    LegalDocument = apps.get_model("terms", "LegalDocument")
    LegalDocument.objects.filter(language="kz").update(language="kk")


def migrate_kk_to_kz(apps, schema_editor):
    LegalDocument = apps.get_model("terms", "LegalDocument")
    LegalDocument.objects.filter(language="kk").update(language="kz")


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0003_alter_legaldocument_language"),
    ]

    operations = [
        migrations.RunPython(migrate_kz_to_kk, migrate_kk_to_kz),
        migrations.AlterField(
            model_name="legaldocument",
            name="language",
            field=models.CharField(
                choices=[
                    ("ru", "Русский"),
                    ("en", "English"),
                    ("uk", "Українська"),
                    ("be", "Белорусский"),
                    ("kk", "Қазақша"),
                ],
                max_length=2,
                verbose_name="Язык",
            ),
        ),
    ]
