# Generated by Django 6.1.1 on 2026-09-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0004_alter_legaldocument_language_kk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legaldocument',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='legaldocument',
            constraint=models.UniqueConstraint(fields=('doc_type', 'language'), name='unique_legaldocument_doc_type_language'),
        ),
    ]
