# Generated by Django 5.2.3 on 2025-11-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                max_length=80,
                null=True,
                upload_to='staticfiles/ugc/user_avatars'),
        ),
    ]
