# Generated by Django 5.2.3 on 2025-11-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
