# Generated by Django 5.2.3 on 2025-11-16 13:46

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_discord_alter_user_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(max_length=80, null=True, upload_to=apps.user.models.User.unique_avatar_path),
        ),
    ]
