# Generated by Django 5.2.3 on 2025-11-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userban',
            name='ip',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
