# Generated by Django 5.2.3 on 2025-11-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_useractivitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ip',
        ),
    ]
