# Generated by Django 6.0 on 2025-12-25 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevRequestsModel',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('github',
                 models.URLField(
                     max_length=128)),
                ('mail',
                 models.EmailField(
                     max_length=128)),
                ('about_you',
                 models.CharField(
                     max_length=1000)),
                ('why_you_choose_us',
                 models.CharField(
                     max_length=250)),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='developer_status_requests',
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
