# Generated by Django 6.0 on 2025-12-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_devrequestsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devrequestsmodel',
            options={'ordering': ['-id'], 'verbose_name': 'Заявка на статус разработчика', 'verbose_name_plural': 'Заявки на статус разработчика'},
        ),
        migrations.AlterField(
            model_name='devrequestsmodel',
            name='about_you',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='devrequestsmodel',
            name='why_you_choose_us',
            field=models.TextField(max_length=250),
        ),
    ]
