# Generated by Django 6.0 on 2026-01-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_devrequestsmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedUsername',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('word',
                 models.CharField(
                     max_length=50,
                     unique=True,
                     verbose_name='Запрещённый юзернейм')),
                ('is_regex',
                 models.BooleanField(
                     default=False,
                     verbose_name='Это регулярное выражение? (regex type)')),
            ],
            options={
                'verbose_name': 'Бан-ворд (юзернейм)',
                'verbose_name_plural': 'Бан-ворды (юзернеймы)',
            },
        ),
    ]
