# Generated by Django 6.0 on 2026-01-22 15:21

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_blacklistedusername'),
    ]

    operations = [
        TrigramExtension(),
    ]
