# Generated by Django 6.0 on 2026-02-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_invited_by_invitetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetoken',
            name='code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
