# Generated by Django 6.0 on 2026-03-12 20:46

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_blacklistedusername_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=80, null=True, upload_to=apps.user.models.User.unique_avatar_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='discord',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, max_length=45, null=True),
        ),
    ]
