# Generated by Django 6.0 on 2026-03-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_legaldocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalDocument',
        ),
    ]
