# Generated by Django 6.0 on 2026-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_user_avatar_user_avatar_id_user_avatar_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
    ]
