# Generated by Django 6.0 on 2026-03-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_discord_alter_user_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default='Пока что, описания тут нету', max_length=255),
        ),
    ]
