# Generated by Django 6.0 on 2026-03-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                error_messages={
                    'unique': 'ERROR_EMAIL_ALREADY_IN_USE'},
                max_length=254,
                unique=True),
        ),
    ]
