# Generated by Django 6.0 on 2026-03-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userban',
            name='ban_by_ip',
            field=models.BooleanField(default=False, verbose_name='Блокировка по IP'),
        ),
        migrations.AddField(
            model_name='userban',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения'),
        ),
        migrations.AddField(
            model_name='userban',
            name='is_permanent',
            field=models.BooleanField(default=False, verbose_name='Постоянная блокировка'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='userban',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Причина'),
        ),
    ]
