# Generated by Django 6.0 on 2026-03-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_userban_ban_by_ip_userban_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openvk',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
