# Generated by Django 6.0 on 2026-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_user_openvk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitetoken',
            options={'verbose_name': 'Токен приглашения', 'verbose_name_plural': 'Токены приглашения'},
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
