# Generated by Django 6.0 on 2026-04-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_invitetoken_options_user_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default='Пользователь не оставил описание, но надеемся, что он крут', max_length=255),
        ),
    ]
