# Generated by Django 6.0 on 2026-04-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fingerprint',
        ),
    ]
