# Generated by Django 6.0 on 2026-05-10 12:21

import apps.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_user_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'ERROR_EMAIL_ALREADY_IN_USE'}, max_length=254, unique=True, validators=[apps.user.validators.validate_email_mx]),
        ),
    ]
