# Generated by Django 6.0 on 2026-05-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_splash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
