# Generated by Django 6.0.3 on 2026-05-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
