# Generated by Django 6.0.7 on 2026-07-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_nospamrule_nospamevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nospamrule',
            new_name='user_nospam_is_enab_bc8062_idx',
            old_name='user_nospam_is_enabl_4ef28f_idx',
        ),
        migrations.RenameIndex(
            model_name='nospamrule',
            new_name='user_nospam_match_t_4379d4_idx',
            old_name='user_nospam_match_t_7f3b10_idx',
        ),
    ]
