# Generated by Django 6.0.7 on 2026-08-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_rename_user_nospam_is_enabl_4ef28f_idx_user_nospam_is_enab_bc8062_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nospamrule',
            name='match_type',
            field=models.CharField(choices=[('email_domain', 'Домен email'), ('email_regex', 'Email regex'), ('username_regex', 'Username regex'), ('ip_cidr', 'IP CIDR'), ('user_agent_regex', 'User-Agent regex'), ('country_code', 'Код страны'), ('invite_pattern', 'Паттерн invite'), ('request_rate_signal', 'Сигнал скорости запросов'), ('user_id_range', 'Диапазон ID пользователя')], db_index=True, max_length=32, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='nospamrule',
            name='pattern',
            field=models.CharField(blank=True, default='', help_text='Для диапазона ID: min:max, например 100:500', max_length=255, verbose_name='Паттерн'),
        ),
    ]
