# Generated by Django 6.0.7 on 2026-09-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_nospamrule_match_type_alter_nospamrule_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_layout',
            field=models.CharField(choices=[('rich', 'Содержательная'), ('compact', 'Сокращённая')], default='rich', max_length=16, verbose_name='Вид главной страницы'),
        ),
    ]
