# Generated by Django 6.1.1 on 2026-09-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_home_recommendations'),
        ('user', '0035_lunapassportlink'),
    ]

    operations = [
    ]
