# Generated by Django 6.1.1 on 2026-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_merge_0034_home_recommendations_0035_lunapassportlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trusted',
            field=models.BooleanField(
                default=False,
                help_text='Заявки на публикацию и правку приложений/дистрибуций одобряются автоматически, но всё равно логируются и отправляются в Telegram',
                verbose_name='Доверенный автор'),
        ),
    ]
