# Generated by Django 6.1.1 on 2026-09-26 14:58

import apps.user.validators
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0037_user_is_trusted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedusername',
            name='word',
            field=models.CharField(max_length=50, verbose_name='Запрещённый юзернейм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'ERROR_EMAIL_ALREADY_IN_USE'}, max_length=254, validators=[apps.user.validators.validate_email_mx]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='blacklistedusername',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('word',), name='unique_active_blacklisted_username_word'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('email',), name='unique_active_user_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('username',), name='unique_active_user_username'),
        ),
    ]
