# Generated by Django 6.1.1 on 2026-09-29 15:34

import apps.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_user_is_trusted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'ERROR_USERNAME_ALREADY_IN_USE'}, help_text='Required. 150 characters or fewer. English letters, digits and . _ - only.', max_length=150, unique=True, validators=[apps.user.validators.validate_english_username], verbose_name='username'),
        ),
    ]
