# Generated by Django 6.1.1 on 2026-10-02

import apps.user.models
import apps.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0038_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.models.SafeDeleteUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='blacklistedusername',
            name='word',
            field=models.CharField(max_length=50, verbose_name='Запрещённый юзернейм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'ERROR_EMAIL_ALREADY_IN_USE'}, max_length=254, validators=[apps.user.validators.validate_email_mx]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'ERROR_USERNAME_ALREADY_IN_USE'}, help_text='Required. 150 characters or fewer. English letters, digits and . _ - only.', max_length=150, validators=[apps.user.validators.validate_english_username], verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='blacklistedusername',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('word',), name='unique_active_blacklisted_username_word'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('email',), name='unique_active_user_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('username',), name='unique_active_user_username'),
        ),
    ]
