# Generated by Django 6.0 on 2026-03-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalDocument',
        ),
    ]
